# Generated by Django 5.0.4 on 2024-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=21)),
                ('lastName', models.CharField(max_length=21)),
                ('travelPoints', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
